export enum GeneratorActionTypes {
  CHANGE_TEXT_TEMPLATE = '@generator/CHANGE_TEXT_TEMPLATE',
  CHANGE_GENERATOR_NAME = '@generator/CHANGE_GENERATOR_NAME',
  ADD_TABLE = '@generator/ADD_TABLE',
  REMOVE_TABLE = '@generator/REMOVE_TABLE',

  CHANGE_TABLE_NAME = '@table/CHANGE_TABLE_NAME',
  ADD_TABLE_ENTRY = '@table/ADD_TABLE_ENTRY',
  REMOVE_TABLE_ENTRY = '@table/REMOVE_TABLE_ENTRY',
  CHANGE_TABLE_ENTRY = '@table/CHANGE_TABLE_ENTRY',

  UPDATE_STATE_FROM_FILE = '@app/UPDATE_STATE_FROM_FILE',
}